// Code generated by MockGen. DO NOT EDIT.
// Source: internal/shared/context/context.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockContext) Bind(obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockContextMockRecorder) Bind(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockContext)(nil).Bind), obj)
}

// BindHeader mocks base method.
func (m *MockContext) BindHeader(obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindHeader", obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindHeader indicates an expected call of BindHeader.
func (mr *MockContextMockRecorder) BindHeader(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindHeader", reflect.TypeOf((*MockContext)(nil).BindHeader), obj)
}

// BindJSON mocks base method.
func (m *MockContext) BindJSON(obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindJSON", obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindJSON indicates an expected call of BindJSON.
func (mr *MockContextMockRecorder) BindJSON(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindJSON", reflect.TypeOf((*MockContext)(nil).BindJSON), obj)
}

// BindQuery mocks base method.
func (m *MockContext) BindQuery(obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindQuery", obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindQuery indicates an expected call of BindQuery.
func (mr *MockContextMockRecorder) BindQuery(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindQuery", reflect.TypeOf((*MockContext)(nil).BindQuery), obj)
}

// BindURI mocks base method.
func (m *MockContext) BindURI(obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindURI", obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindURI indicates an expected call of BindURI.
func (mr *MockContextMockRecorder) BindURI(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindURI", reflect.TypeOf((*MockContext)(nil).BindURI), obj)
}

// Get mocks base method.
func (m *MockContext) Get(key string) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockContextMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContext)(nil).Get), key)
}

// GetClientIP mocks base method.
func (m *MockContext) GetClientIP() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientIP")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetClientIP indicates an expected call of GetClientIP.
func (mr *MockContextMockRecorder) GetClientIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientIP", reflect.TypeOf((*MockContext)(nil).GetClientIP))
}

// GetContext mocks base method.
func (m *MockContext) GetContext() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// GetContext indicates an expected call of GetContext.
func (mr *MockContextMockRecorder) GetContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockContext)(nil).GetContext))
}

// GetCookie mocks base method.
func (m *MockContext) GetCookie(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCookie", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCookie indicates an expected call of GetCookie.
func (mr *MockContextMockRecorder) GetCookie(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCookie", reflect.TypeOf((*MockContext)(nil).GetCookie), name)
}

// GetHeader mocks base method.
func (m *MockContext) GetHeader(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeader", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHeader indicates an expected call of GetHeader.
func (mr *MockContextMockRecorder) GetHeader(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeader", reflect.TypeOf((*MockContext)(nil).GetHeader), key)
}

// GetUserAgent mocks base method.
func (m *MockContext) GetUserAgent() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAgent")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserAgent indicates an expected call of GetUserAgent.
func (mr *MockContextMockRecorder) GetUserAgent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAgent", reflect.TypeOf((*MockContext)(nil).GetUserAgent))
}

// GetUserID mocks base method.
func (m *MockContext) GetUserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockContextMockRecorder) GetUserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockContext)(nil).GetUserID))
}

// JSON mocks base method.
func (m *MockContext) JSON(code int, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JSON", code, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// JSON indicates an expected call of JSON.
func (mr *MockContextMockRecorder) JSON(code, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSON", reflect.TypeOf((*MockContext)(nil).JSON), code, v)
}

// Param mocks base method.
func (m *MockContext) Param(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Param", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// Param indicates an expected call of Param.
func (mr *MockContextMockRecorder) Param(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Param", reflect.TypeOf((*MockContext)(nil).Param), name)
}

// RemoveCookie mocks base method.
func (m *MockContext) RemoveCookie(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveCookie", name)
}

// RemoveCookie indicates an expected call of RemoveCookie.
func (mr *MockContextMockRecorder) RemoveCookie(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCookie", reflect.TypeOf((*MockContext)(nil).RemoveCookie), name)
}

// Set mocks base method.
func (m *MockContext) Set(key string, value any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, value)
}

// Set indicates an expected call of Set.
func (mr *MockContextMockRecorder) Set(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockContext)(nil).Set), key, value)
}

// SetCookie mocks base method.
func (m *MockContext) SetCookie(name, value string, maxAge int, path, domain string, secure, httpOnly bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCookie", name, value, maxAge, path, domain, secure, httpOnly)
}

// SetCookie indicates an expected call of SetCookie.
func (mr *MockContextMockRecorder) SetCookie(name, value, maxAge, path, domain, secure, httpOnly interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCookie", reflect.TypeOf((*MockContext)(nil).SetCookie), name, value, maxAge, path, domain, secure, httpOnly)
}

// SetHeader mocks base method.
func (m *MockContext) SetHeader(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHeader", key, value)
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockContextMockRecorder) SetHeader(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockContext)(nil).SetHeader), key, value)
}
