// Code generated by MockGen. DO NOT EDIT.
// Source: internal/shared/uow/unit_of_work.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// DeferErrorContext mocks base method.
func (m *MockUnitOfWork) DeferErrorContext(ctx context.Context, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeferErrorContext", ctx, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeferErrorContext indicates an expected call of DeferErrorContext.
func (mr *MockUnitOfWorkMockRecorder) DeferErrorContext(ctx, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeferErrorContext", reflect.TypeOf((*MockUnitOfWork)(nil).DeferErrorContext), ctx, err)
}

// StartContext mocks base method.
func (m *MockUnitOfWork) StartContext(ctx context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartContext", ctx)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// StartContext indicates an expected call of StartContext.
func (mr *MockUnitOfWorkMockRecorder) StartContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartContext", reflect.TypeOf((*MockUnitOfWork)(nil).StartContext), ctx)
}
